FinalProjectRestorant/ViewComponents/FooterViewComponent.cs
using FinalProjectRestorant.DAL;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace FinalProjectRestorant.ViewComponents
{
    public class FooterViewComponent:ViewComponent
    {
        public AppDbContext _context { get; }
        public FooterViewComponent(AppDbContext context)
        {
            _context = context;
        }
        public async Task<IViewComponentResult> InvokeAsync()
        {
            var model = _context.Settings.FirstOrDefault();
            return  View(await Task.FromResult(model));
        }
    }
}

FinalProjectRestorant/ViewComponents/HeaderViewComponent.cs
using FinalProjectRestorant.DAL;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace FinalProjectRestorant.ViewComponents
{
    public class HeaderViewComponent:ViewComponent
    {
        public AppDbContext _context { get; }
        public HeaderViewComponent(AppDbContext context)
        {
            _context = context;
        }

        public async Task<IViewComponentResult> InvokeAsync()
        {
            var model = _context.Settings.FirstOrDefault();
            return View(await Task.FromResult(model));
        }

    }
}

FinalProjectRestorant/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">

  <head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css" />
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.5.0.js"></script>
    <link rel="stylesheet" href="https://unpkg.com/aos@next/dist/aos.css" />
    <link rel="stylesheet" href="~/../assets/contact.css">
    <link rel="stylesheet" href="~/../assets/chef.css" />
    <title>OurRestuorant</title>
 </head>

  <body>
      @await Component.InvokeAsync("Header")
      @RenderBody()
      @await Component.InvokeAsync("Footer")


      <script src="https://unpkg.com/aos@next/dist/aos.js"></script>
      <script>
          AOS.init();
      </script>
      <script src="../js/index.js"></script>

  </body>
  
</html>